
INSERT INTO USER(LOGIN, PASSWORD) VALUES ('admin', '$2a$11$tb8jyXAdsXzG7GpPcUE.DeBySVK0YYxtZc2484sZuZqSva1Vh/Oa.');
INSERT INTO INVESTMENT(ID, END_INVESTMENT_DATE, INTEREST, INVESTMENT_BALANCE, START_INVESTMENT_DATE, USER_ID )VALUES ('1', NULL,'10.00','1000.00',NULL ,'1');
INSERT INTO INVESTMENT(ID, END_INVESTMENT_DATE, INTEREST, INVESTMENT_BALANCE, START_INVESTMENT_DATE, USER_ID )VALUES ('2', NULL,'20.00','2000.00',NULL ,'1');
INSERT INTO INVESTMENT(ID, END_INVESTMENT_DATE, INTEREST, INVESTMENT_BALANCE, START_INVESTMENT_DATE, USER_ID )VALUES ('3', NULL,'30.00','3000.00',NULL ,'1');
